name: Go Build
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Install Octopus Deploy CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: Install Dependencies
        run: go get ./...
        shell: bash
      - name: List Dependencies
        run: go list -m all > dependencies.txt
        shell: bash
      - name: Collect Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Dependencies
          path: dependencies.txt
      - name: List Dependency Updates
        run: go list -u -m -f "{{if .Update}}{{.}}{{end}}" all > dependencyUpdates.txt
        shell: bash
      - name: Collect Dependency Updates
        uses: actions/upload-artifact@v2
        with:
          name: Dependencies Updates
          path: dependencyUpdates.txt
      - name: Test
        run: go install gotest.tools/gotestsum@latest; gotestsum --junitfile results.xml
        shell: bash
      - if: always()
        name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Go Tests
          path: results.xml
          reporter: java-junit
          fail-on-error: 'false'
      - run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o bootstrap cmd/lambda/lambda.go
      - run: zip OctopusSubscriptionListener.zip bootstrap
      # These are the dependencies that need to be manually installed to support https://github.com/ehsaniara/maven-repository-aws-s3
      # Typically the deployment of artifacts is configured in a pom.xml file and executed as part of an application's build.
      # However, because we are using the Maven feed to host arbitrary artifacts, it is nice to be able to call
      # "mvn deploy:deploy-file" against any file. This means we don't have the luxury of referencing the
      # "com.github.ehsaniara:maven-repository-aws-s3" dependency directly in a pom.xml file and having all the necessary
      # transitive dependencies downloaded for us. Instead, we must download these dependencies manually.
      - name: Install maven-repository-aws-s3 dependencies
        run: |
          HOME=$(dirname $(readlink -f $(which mvn)))
          for dep in "com.github.ehsaniara:maven-repository-aws-s3:1.2.11:jar" "org.apache.httpcomponents:httpcore:4.4.16:jar" "com.amazonaws:aws-java-sdk-s3:1.12.405:jar" "com.amazonaws:aws-java-sdk-core:1.12.405:jar" "com.fasterxml.jackson.core:jackson-core:2.14.2:jar" "com.fasterxml.jackson.core:jackson-databind:2.14.2:jar" "com.fasterxml.jackson.core:jackson-annotations:2.14.2:jar" "joda-time:joda-time:2.12.2:jar" "org.apache.httpcomponents:httpclient:4.5.14:jar" "commons-io:commons-io:2.12.0"
          do
             split=(${dep//:/ })
             mvn dependency:get \
              --batch-mode \
              -DrepoUrl=https://repo.maven.apache.org/maven2 \
              -Dartifact=${dep} \
              -Ddest=${HOME}/../lib/${split[0]}.${split[1]}.jar
          done
        shell: bash

      - name: Configure maven-repository-aws-s3
        run: |
          cat <<EOT > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>octopus-sales-public-snapshot</id>
                <username>${{ secrets.AWS_ACCESS_KEY_ID }}</username>
                <password>${{ secrets.AWS_SECRET_ACCESS_KEY }}</password>
                <configuration>
                  <region>ap-southeast-2</region>
                  <publicRepository>true</publicRepository>
                </configuration>
              </server>
              <server>
                <id>octopus-sales-public-release</id>
                <username>${{ secrets.AWS_ACCESS_KEY_ID }}</username>
                <password>${{ secrets.AWS_SECRET_ACCESS_KEY }}</password>
                <configuration>
                  <region>ap-southeast-2</region>
                  <publicRepository>true</publicRepository>
                </configuration>
              </server>
            </servers>
          </settings>
          EOT
        shell: bash

      # The Lambda package is pushed to the Octopus maven repo.
      - name: Push Lambda Package
        run: |
          mvn deploy:deploy-file \
            --batch-mode \
            "-DgroupId=com.octopus" \
            "-DartifactId=octopus-subscription-listener-lambda" \
            "-Dversion=${{ steps.determine_version.outputs.semVer }}" \
            "-Dpackaging=zip" \
            "-Dfile=OctopusSubscriptionListener.zip" \
            "-DrepositoryId=octopus-sales-public-snapshot" \
            "-Durl=s3://octopus-sales-public-maven-repo/snapshot"
        shell: bash

permissions:
  id-token: write
  checks: write
  contents: write
